version: "3"

services:
  billing-server:
    container_name: NODEJS_SERVER_BILLING
    build: "."
    volumes:
      - ./src:/node-app
      - ./node_modules:/node-app/node_modules
    environment:
      NODE_ENV: development
    ports:
      - "3030:3030"

networks:
  default:
    external:
      name: customnet
